# Generated by Django 5.2.17 on 2026-10-02 09:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[accounts.validators.validate_list_email])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'admin email',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[accounts.validators.validate_list_email])),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(choices=[('#d93025', 'Red'), ('#e8710a', 'Orange'), ('#c9a100', 'Gold'), ('#7cb342', 'Lime'), ('#188038', 'Green'), ('#12a4af', 'Teal'), ('#1a73e8', 'Blue'), ('#3f51b5', 'Indigo'), ('#9334e6', 'Purple'), ('#d01884', 'Pink'), ('#8d6e63', 'Brown'), ('#5f6368', 'Gray')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
