# Generated by Django 5.2.17 on 2026-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='color',
            field=models.CharField(choices=[('#d93025', 'Red'), ('#e8710a', 'Orange'), ('#c9a100', 'Gold'), ('#7cb342', 'Lime'), ('#188038', 'Green'), ('#12a4af', 'Teal'), ('#1a73e8', 'Blue'), ('#3f51b5', 'Indigo'), ('#9334e6', 'Purple'), ('#d01884', 'Pink'), ('#8d6e63', 'Brown'), ('#5f6368', 'Gray')], error_messages={'unique': 'Another driver already has this color.'}, max_length=7, unique=True),
        ),
    ]
