# Generated by Django 5.2.17 on 2026-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_revoke_google_account_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="color",
            field=models.CharField(
                choices=[
                    ("#d93025", "Red"),
                    ("#e8710a", "Orange"),
                    ("#c9a100", "Gold"),
                    ("#7cb342", "Lime"),
                    ("#188038", "Green"),
                    ("#12a4af", "Teal"),
                    ("#1a73e8", "Blue"),
                    ("#3f51b5", "Indigo"),
                    ("#9334e6", "Purple"),
                    ("#d01884", "Pink"),
                    ("#8d6e63", "Brown"),
                    ("#5f6368", "Gray"),
                    ("#f28b82", "Light red"),
                    ("#fbb26a", "Light orange"),
                    ("#f2d24b", "Light gold"),
                    ("#c0dd8a", "Light lime"),
                    ("#6fcf8f", "Light green"),
                    ("#7fd8d8", "Light teal"),
                    ("#7fbcff", "Light blue"),
                    ("#a99cf0", "Light indigo"),
                    ("#dfa2f2", "Light purple"),
                    ("#f7a1cf", "Light pink"),
                    ("#d4a98c", "Light brown"),
                    ("#c4c7c5", "Light gray"),
                ],
                error_messages={"unique": "Another driver already has this color."},
                max_length=7,
                unique=True,
            ),
        ),
    ]
