# Generated by Django 5.2.17 on 2026-10-08 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_driver_24_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                        ]
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="accounts.driver",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start"],
            },
        ),
    ]
