# Generated by Django 5.2.17 on 2026-10-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver_shifts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverShift',
        ),
    ]
