# Generated by Django 5.2.17 on 2026-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_recreate_driver_shifts"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="purged_rides",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
