# Generated by Django 5.2.17 on 2026-10-03 06:30

import django.db.models.deletion
import rides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_revoke_google_account_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(max_length=120)),
                ('rider_phone', models.CharField(help_text='10 digits, e.g. 8055550123', max_length=10)),
                ('rider_email', models.EmailField(max_length=254)),
                ('pickup_time', models.DateTimeField()),
                ('pickup_name', models.CharField(max_length=120)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_name', models.CharField(max_length=120)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('rider_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('link_token', models.CharField(default=rides.models.new_link_token, editable=False, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='accounts.driver')),
            ],
            options={
                'ordering': ['pickup_time'],
                'indexes': [models.Index(fields=['pickup_time'], name='rides_ride_pickup__a1df25_idx'), models.Index(fields=['driver', 'pickup_time'], name='rides_ride_driver__23cb0d_idx'), models.Index(fields=['rider_phone'], name='rides_ride_rider_p_6584ec_idx')],
            },
        ),
    ]
