# Generated by Django 5.2.17 on 2026-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='dropoff_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='dropoff_lng',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pickup_lng',
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
