# Generated by Django 5.2.17 on 2026-10-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_driver_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
