# Generated by Django 5.2.17 on 2026-10-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ride_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rider_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
