# Generated by Django 5.2.17 on 2026-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0005_alter_ride_rider_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="notes",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
