# Generated by Django 5.2.17 on 2026-10-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0006_ride_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="series",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
